services:
  baileyai:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: baileyai-inference-api

    ports:
      - "8000:8000"

    env_file:
      - ../.env

    gpus: all

    restart: unless-stopped